app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView

# from core.views import myfirstview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hosdigital/', include('core.urls')),
    path('', IndexView.as_view(), name='index'),
    path('login/', include('core.login.urls')),
    path('reports/', include('core.reports.urls')),
]

app/core/urls.py
from django.urls import path

from core.views.agendamiento.cita import AgendamientoCreateView
from core.views.cita.views import *
from core.views.especialidad.views import *

# Nombre del bloque de rutas secundarias

app_name = 'hosdigital'

urlpatterns = [
    # Especialidad
    path('especialidad/list', especialidadListView.as_view(), name='especialidad_list'),
    path('especialidad/create', especialidadCreateView.as_view(), name='especialidad_createview'),
    path('especialidad/edit/<int:pk>/', especialidadUpdateView.as_view(), name='especialidad_updateview'),
    path('especialidad/delete/<int:pk>/', especialidadDeleteView.as_view(), name='especialidad_delete'),
    # Cita
    path('cita/list', citaListView.as_view(), name='cita_list'),
    path('cita/create', citaCreateView.as_view(), name='cita_createview'),
    path('cita/edit/<int:pk>/', citaUpdateView.as_view(), name='cita_updateview'),
    path('cita/delete/<int:pk>/', citaDeleteView.as_view(), name='cita_delete'),
    # Agendamiento
    path('agendamiento/cita', AgendamientoCreateView.as_view(), name='agendamiento_cita'),
]

app/templates/hzt/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'hzt/header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>Example 3.0</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    </body>
{% endblock %}

app/templates/hzt/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <div class="container">
        <a href="#" class="navbar-brand">
            <img src="{% static '/img/logo1.png' %}" alt="AdminLTE Logo"
                 class="brand-image"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Hades</span>
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link"><i class="fas fa-home"></i> INICIO</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'hosdigital:especialidad_list' %}" class="dropdown-item"><i class="fas fa-truck-loading"></i> Categorías</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-boxes"></i> Productos</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-users"></i> Clientes</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Ventas</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="fas fa-users-cog"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">
                        Último Acceso: 12 de Abril de 2020
                    </span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-edit mr-2"></i> Editar perfil
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-lock mr-2"></i> Editar password
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">
                        <p>Este sistema te permitira realizar diferentes actividades</p>
                    </a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i class="fas fa-power-off" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>